version: '3'
services:
  elastalert:
    image: crimsoncorelabs/elastalert
    container_name: elastalert
    restart: unless-stopped
    volumes:
      - /opt/threathunt/elastalert/config:/opt/elastalert/config
      - /opt/threathunt/elastalert/rules:/opt/elastalert/rules
      - /opt/threathunt/elastalert/log:/opt/elastalert/log
      - /opt/threathunt/elastalert/rule_templates:/opt/elastalert/rule_templates
    networks:
      - elastic    
networks:
  elastic:
    driver: bridge
