version: '3'
services:
  logstashMQ:
    image: docker.elastic.co/logstash/logstash:7.6.2
    container_name: logstashMQ    
    ports:
     - 5044:5044
    restart: unless-stopped
    volumes:
    - /opt/threathunt/logstashMQ/pipeline/:/usr/share/logstash/pipeline/
    - /opt/threathunt/logstashMQ/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
