version: '3'
services:
  guacamole:
    image: tunip/guacamole
    container_name: guacamole
    restart: unless-stopped
    volumes:
      - /opt/threathunt/guacamole/config:/config
    ports:
      - 8080:8080
    networks:
      - elastic
  guacamole-daemon:
    image: guacamole/guacd
    container_name: guacamole_daemon
    restart: unless-stopped
    ports:
      - 4822:4822
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
