version: '3'
services:
  logstash:
    image: crimsoncorelabs/logstashrest
    container_name: logstash_rest
    ports:
     - 5044:5044
     - 5045:5045
     - 5046:5046
    restart: unless-stopped
    volumes:
    - /opt/threathunt/logstash/pipeline/:/usr/share/logstash/pipeline/
    - /opt/threathunt/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    - /opt/threathunt/logstash/patterns:/usr/share/logstash/patterns
    - /opt/threathunt/logstash/pki/:/usr/share/logstash/pki
    networks:
      - elastic

networks:
  elastic:
    driver: bridge