rules_folder: rules
run_every:
    seconds: 30
buffer_time:
    seconds: 45
es_host: es01
es_port: 9200
alert_time_limit:
    days: 1
writeback_index: elastalert_status

#alert_text: "Index: {0} \nEvent_Timestamp: {1} \nBeat_Name: {2} \nUser_Name: {3} \nHost_Name: {4} \nLog_Name: {5} \nOriginal_Message: \n\n{6}"
#alert_text_type: alert_text_only
#alert_text_args: ["_index","@timestamp","beat.name","user_name","host_name","log_name","z_original_message"]

alert_text: "{2} Endpoint: {0} CommandLine: {1}"
alert_text_type: alert_text_only
alert_text_args:
- host.name
- winlog.event_data.CommandLine
- "@timestamp"

#alert:
#- "slack"
#slack:
#slack_webhook_url: "https://hooks.slack.com/services/###pasteyourwebhookhere###"